version: '3'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
           - '4000:8080'
        links:
          - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
          - '27017:27017'
    mongo-express:
       image: mongo-express
       restart: always
       volumes:
          -./mongoDB:/docker-entrypoint-initdb.d
       ports:
          - 8081:8081
       environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: ManuJoseCamilo2000
