version: '3'
services:
  # app:
  #   container_name: project3
  #   restart: always
  #   build: .
  #   ports:
  #     - '8080:5000'
  #   external_links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27016:27017'
    volumes:
      - ./mongo_data:/data/db
      - ./mongo_init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: restaurants
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo